name: Test ANK

on:
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # cancel-in-progress: true

jobs:
  build-and-test-on-pr:
    name: Buil and Test on PR
    
    runs-on: ubuntu-latest

    steps:
      - name: Build the code
        run: |
            echo "Starting code building
