name: Test ANK

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build the code
      - run: |
            echo "Starting code building"
            sleep 1m
            echo "Finis code building"
            echo "Test 1"
