name: Test ANK

on:
  pull_request:
    branches: [master]

concurrency:
  group: My group
  # cancel-in-progress: true

jobs:
  build-and-test-on-pr:
    name: Build and Test on PR
    
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Starting code building. Test 2"
          sleep 1m
          echo "Finish code building"
