name: Test ANK

on: [push]
#  push:
#    branches:
#      - master

permissions:
  contents: read

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
      - run: |
            git status
      - run: echo "${{ github.workflow }}-${{ github.ref }}"

#      - name: Setup Java JDK
#        uses: actions/setup-java@v3.13.0
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name: Build with Gradle
#        uses: gradle/gradle-build-action@v2.9.0
#        with:
#          gradle-version: 7.6
#          arguments: build

#      - name: Push to dokku
#        uses: dokku/github-action@master
#        with:
#          branch: 'master'
#          git_push_flags: '--force'
#          git_remote_url: ${{ vars.STAGE_REMOTE_URL }}
#          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
